"""add ai fields to issues

Revision ID: 065be7cf25ec
Revises: 27ca5263d46d
Create Date: 2026-03-28 19:24:55.897440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065be7cf25ec'
down_revision: Union[str, Sequence[str], None] = '27ca5263d46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('ai_suggested_description', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('ai_is_resolved', sa.Boolean(), nullable=True))
    op.add_column('issues', sa.Column('ai_resolution_quality', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('ai_resolution_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'ai_resolution_notes')
    op.drop_column('issues', 'ai_resolution_quality')
    op.drop_column('issues', 'ai_is_resolved')
    op.drop_column('issues', 'ai_suggested_description')
    # ### end Alembic commands ###
