"""announcement push outbox and explicit reporter FK

Revision ID: x6y7z8a9b0
Revises: w5x6y7z8a9
Create Date: 2026-07-28 15:40:00.000000

1. ``announcements.push_dispatched_at`` — the outbox marker.

   Creating an announcement used to fan out its push notifications inline: one
   INSERT, one COMMIT and one blocking FCM call per recipient, inside the POST
   handler. A state-scoped announcement to 200k citizens was 200k sequential
   commits in one HTTP request, and the whole loop sat inside
   ``except Exception: logger.warning("non-fatal")`` — so a total delivery
   failure still returned 201 Created with no indication.

   Delivery now happens in the ``jobs`` service, which can take its time and can
   retry on the next cycle. Existing rows are backfilled as already-dispatched:
   they were sent (or attempted) under the old inline path, and leaving them NULL
   would re-notify every recipient of every historical announcement on the first
   cycle after deploy.

2. ``issues.reporter_id`` gains an explicit ``ON DELETE RESTRICT``. It was the
   only user FK in the schema with no action declared, so it inherited NO
   ACTION. Same behaviour, stated intent: an issue is a civic record that
   outlives the reporter's account, and erasure is a soft delete.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'x6y7z8a9b0'
down_revision: Union[str, Sequence[str], None] = 'w5x6y7z8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── announcement outbox ───────────────────────────────────────────────────
    op.add_column(
        "announcements",
        sa.Column("push_dispatched_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_announcements_push_dispatched_at",
        "announcements",
        ["push_dispatched_at"],
    )
    # Treat everything that already exists as delivered — see the note above.
    op.execute("UPDATE announcements SET push_dispatched_at = created_at")

    # ── explicit ON DELETE RESTRICT on issues.reporter_id ────────────────────
    # The existing constraint name is generated by Postgres; drop by that name
    # and recreate with the action spelled out.
    op.drop_constraint("issues_reporter_id_fkey", "issues", type_="foreignkey")
    op.create_foreign_key(
        "issues_reporter_id_fkey",
        "issues",
        "users",
        ["reporter_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint("issues_reporter_id_fkey", "issues", type_="foreignkey")
    op.create_foreign_key(
        "issues_reporter_id_fkey", "issues", "users", ["reporter_id"], ["id"]
    )
    op.drop_index("ix_announcements_push_dispatched_at", table_name="announcements")
    op.drop_column("announcements", "push_dispatched_at")
