"""add_worker_location_and_issue_escalation_fields

Revision ID: 6478303af1f9
Revises: 065be7cf25ec
Create Date: 2026-03-28 19:54:47.752456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6478303af1f9'
down_revision: Union[str, Sequence[str], None] = '065be7cf25ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('is_escalated', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('issues', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('is_blocked', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('issues', sa.Column('blocked_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_updated_at')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('issues', 'blocked_reason')
    op.drop_column('issues', 'is_blocked')
    op.drop_column('issues', 'escalated_at')
    op.drop_column('issues', 'is_escalated')
    # ### end Alembic commands ###
