"""add_rejected_by_ids_to_issues

Revision ID: f7bdeda7fdb3
Revises: g6b7c8d9e0f1
Create Date: 2026-04-02 12:18:46.509608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7bdeda7fdb3'
down_revision: Union[str, Sequence[str], None] = 'g6b7c8d9e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('rejected_by_ids', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_index(op.f('ix_issues_is_deleted'), table_name='issues')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_issues_is_deleted'), 'issues', ['is_deleted'], unique=False)
    op.drop_column('issues', 'rejected_by_ids')
    # ### end Alembic commands ###
